### PR TITLE
__bot__ doesn't work

### PR DESCRIPTION
**Pull request by x89**

### CODE REVIEW

**Comment by anlutro** [comment]
Build seems to be failing. Can you investigate @x89 ?

**Comment by x89** [comment]
Dunno, didn't try building it because it's Python.

**Comment by anlutro** [comment]
@x89 Python is easy to "build" if you're on a sensible OS. Are you on Windows or Arch, perhaps?

**Comment by anlutro** [comment]
Separate PR for separate issues please

**Comment by FredG71** [comment]
lol'd

**Comment by x89** [comment]
Gáner go home ur drnk

**Comment by FredG71** [comment]
no u

**Pull request closed without merging**
